### ISSUE TITLE
New ToT prompt is not as good as the original one

### ISSUE THREAD

**Issue by EddieLukeAtmey** [dave1010/tree-of-thought-prompting#2]
Hi, I tried to use the new ToT prompt on ChatGPT3.5 on Poe.

```
Simulate three brilliant, logical experts collaboratively answering a question. Each one verbosely explains their thought process in real-time, considering the prior explanations of others and openly acknowledging mistakes. At each step, whenever possible, each expert refines and builds upon the thoughts of others, acknowledging their contributions. They continue until there is a definitive answer to the question. For clarity, your entire response should be in a markdown table. The question is...
```

I used the question in example (Bob and the ball), and they keep conclude that the ball is in the garden ❌.

The original one, I added a final answer to clarify their conclusion, and it still working great.

```
Imagine three different experts are answering this question.
All experts will write down 1 step of their thinking,
then share it with the group.
Then all experts will go on to the next step, etc.
If any expert realises they're wrong at any point then they leave.
When all experts agreed to a conclusion, they'll all announce it together.
The question is...
```

**Comment by timlincool** [comment]
it's didnt work out
https://chat.openai.com/share/a84b6f14-d3e1-43df-ada9-5b16f748b129

**Comment by lowcountrylee** [comment]
I had trouble with both prompts with 3.5. This one worked well for me. I asked GPT to identify 3 different but appropriate experts to answer the question. I also asked it to score the responses of each expert between 1 and 5.

https://chat.openai.com/share/0cc528aa-79ce-4d57-b2cc-45e07d269200

**Comment by dave1010** [comment]
Thanks @lowcountrylee. Added your prompt here: 31bca6aaae88e8d6aa4052c2dd9cfa63d5649d2e

**Comment by tradeflows-mark** [comment]
hi @dave1010 - good thread - I found in the examples here that ToT worked about 50% of the time on ChatGPT3.5 but 100% of the time on ChatGPT4 

It's a great idea and would be keen to see more tests done. In my examples, I ran 6 retries for each version of ChatGPT. I'll try to do more experiments with it but a great idea that's for sure!

**Comment by dave1010** [comment]
Thanks @tradeflows-mark. Yeah, more tests are definitely needed. Thanks for your input.
