### ISSUE TITLE
Tree-of-thoughts Github repo updates from Princeton paper

### ISSUE THREAD

**Issue by pwwpche** [dave1010/tree-of-thought-prompting#3]
It looks like in Acknowledgements section https://github.com/dave1010/tree-of-thought-prompting#acknowledgements

```
[Tree of Thoughts: Deliberate Problem Solving with Large Language Models](https://arxiv.org/abs/2305.10601), 17 May 2023. [Github](https://github.com/ysymyth/tree-of-thought-llm) (no code as of 22nd May)
```

The authors have their Github repo for official ToT examples set up already (at https://github.com/princeton-nlp/tree-of-thought-llm). Could you help update the link `[Tree of Thoughts](https://github.com/kyegomez/tree-of-thoughts) Github, 21st May 2023` with the official ToT repo? Thanks!

Btw, appreciate your help gathering all the resources in a single place for ToT! This makes it way easier for me to understand ToT from the first glance and also dig deeper!

**Comment by postfix** [comment]
Here you are all the prompts of the official ToT example
https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/prompts/
The text prompt https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/prompts/text.py

**Comment by Confuzu** [comment]
> Here you are all the prompts of the official ToT example https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/prompts/ The text prompt https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/prompts/text.py

the links are dead

**Comment by dave1010** [comment]
Thanks! Link updated.

Looks like that repo has been restructured a bit. Try these:

* https://github.com/princeton-nlp/tree-of-thought-llm/tree/master/src/tot/prompts
* https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/src/tot/prompts/text.py
