### ISSUE TITLE
you sure there is no code to Deliberate Probem Solving with LLMs?

### ISSUE THREAD

**Issue by brando90** [dave1010/tree-of-thought-prompting#5]
see: https://github.com/princeton-nlp/tree-of-thought-llm/tree/master

**Comment by brando90** [comment]
@dave1010

**Comment by dave1010** [comment]
Thanks @brando90. I updated it on Github in #3 but missed the [Medium post](https://medium.com/@dave1010/using-tree-of-thought-prompting-to-boost-chatgpts-reasoning-318914eb0e76). That's now updated too.
